server:
  port: 8761
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: hisrun-registry
  client:
    register-with-eureka: false
    fetch-registry: false