server: 
  port: 3344
  
spring:
  application:
    name:  hisrun-config
  cloud:
    config:
      lable: master
      server:
        git:
          uri: https://github.com/HyanSay/hisrun.git
          search-paths: hisrun-config-repo/**